#!/bin/bash

set -e

FILE="${1/%.elf/.hex}"
FILE="${FILE/%.bin/.hex}"

if [ ! -r "${FILE}" ]; then
    >&2 echo "Usage:"
    >&2 echo "    ${0} program.hex"
    exit 1
fi

env="$(dirname "$0")/../.envrc"
source "$env" "$env"

cat <<EOF | "$JL_PATH/JLinkExe" -Device $JL_DEVICE -If $JL_IF -Speed $JL_SPEED -AutoConnect 1 -NoGui 1
Reset
LoadFile ${FILE}
VerifyBin ${FILE/%.hex/.bin} 0x10000000
Reset
Go
Exit
EOF
