#!/bin/bash

set -e

if [ ! -r "${1}" ]; then
    >&2 echo "Usage:"
    >&2 echo "    ${0} program.elf"
    exit 1
fi

GDBPORT=3333
TELNETPORT=3334
SESSION="JLinkGDBServer.${RANDOM}"

screen -S $SESSION -d -m "$JL_PATH/JLinkGDBServer" -device $JL_DEVICE -if $JL_IF -speed $JL_SPEED -port $GDBPORT -ir -silent -nogui -localhostonly -singlerun -telnetport $TELNETPORT

"$GNU_ARM_PATH/arm-none-eabi-gdb" --se "$1" \
    -ex "target remote localhost:$GDBPORT" \
    -ex "monitor reset" \
    -ex "load" \
    -ex "monitor semihosting breakOnError 1" \
    -ex "monitor semihosting IOClient 1" \
    -ex "monitor semihosting enable" \
    -ex "break main" \
    -ex "monitor reset" \
    -ex "continue" \
    -ex "layout src" || true
screen -qr $SESSION
