#!/bin/bash

set -e

SESSION="JLinkRTTViewer.${RANDOM}"
for port in $(seq 3333 4444); do
    nc -z 127.0.0.1 $port </dev/null &>/dev/null || { RTTPORT=$port; break; };
done
if [ -z "$RTTPORT" ]; then
    >&2 echo "could not find an unused port for the RTT telnet server"
    exit 2
fi

screen -S $SESSION -d -m "$JL_PATH/JLinkExe" -Device $JL_DEVICE -If $JL_IF -Speed $JL_SPEED -AutoConnect 1 -RTTTelnetPort $RTTPORT
screen -m "$JL_PATH/JLinkRTTClientExe" -RTTTelnetPort $RTTPORT || true
screen -r $SESSION -X quit
