#!/bin/bash

set -e

FILE="${1/%.elf/.hex}"

if [ ! -r "${FILE}" ]; then
    >&2 echo "Usage:"
    >&2 echo "    ${0} program.hex"
    exit 1
fi

TEMP=$(mktemp)

cat > "$TEMP" <<EOF
Reset
LoadFile ${FILE}
Reset
Go
Exit
EOF
"$JL_PATH/JLinkExe" -Device $JL_DEVICE -If $JL_IF -Speed $JL_SPEED -AutoConnect 1 -NoGui 1 -commanderscript "$TEMP" || true
rm -f "$TEMP"
