#!/bin/bash

set -e

if [ ! -r "${1}" ]; then
    >&2 echo "Usage:"
    >&2 echo "    ${0} program.elf"
    exit 1
fi

for port in $(seq 3333 4444); do
    nc -z 127.0.0.1 $port </dev/null &>/dev/null || { GDBPORT=$port; break; };
done
if [ -z "$GDBPORT" ]; then
    >&2 echo "could not find an unused port for the gdb server"
    exit 2
fi

SESSION="JLinkGDBServer.${RANDOM}"

screen -S $SESSION -d -m "$(dirname "$0")/jlink-gdb" $GDBPORT

"$GNU_ARM_PATH/arm-none-eabi-gdb" --se "$1" \
    -ex "target remote localhost:$GDBPORT" \
    -ex "monitor reset" \
    -ex "load" \
    -ex "monitor reset" \
    -ex "break main" \
    -ex "continue" \
    -ex "layout src" || true
screen -qr $SESSION || true
