#!/bin/bash

set -e

if [ ! -r "${1}" ]; then
    >&2 echo "Usage:"
    >&2 echo "    ${0} program.bin"
    exit 1
fi

TEMP=$(mktemp)

cat > "$TEMP" <<EOF
Device $JL_DEVICE
SelectInterface SWD
Speed $JL_SPEED
Connect
Reset
Erase
Reset
Exit
EOF
/Applications/SEGGER/JLink/JLinkExe -commanderscript "$TEMP" || rm -f "$TEMP"
